### ISSUE TITLE
Please clarify the license for this code?

### ISSUE THREAD

**Issue by BjarniRunar** [fanout/editor#1]
Hello! Nice work!

I have been looking for something like this, for use in an Open Source project. However, I cannot find anything which clarifies how you feel about others building upon your work. Please forgive me if I didn't look hard enough.

Would you be OK with publishing this under one of the OSI approved Open Source licenses?

Thanks!

**Comment by jkarneges** [comment]
Good point! License file was added today.

**Comment by BjarniRunar** [comment]
Thank you!
